# Generated by Django 6.1.1 on 2026-10-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classapp', '0004_usercoursemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'EmailOTP',
                'ordering': ['-created_at'],
            },
        ),
    ]
